// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410205242_RemoveMaBrandFromCategory")]
    partial class RemoveMaBrandFromCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.article", b =>
                {
                    b.Property<string>("MaBV")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<string>("BVImages")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaLoaiBV")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<string>("NoiDungBV")
                        .HasColumnType("text");

                    b.Property<string>("TenBV")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TomTatBV")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("TrangThaiBV")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("MaBV")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaLoaiBV" }, "fk_article_category");

                    b.ToTable("article");
                });

            modelBuilder.Entity("backend.Models.articlecategory", b =>
                {
                    b.Property<string>("MaLoaiBV")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<string>("TenLoaiBV")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ThuTuBV")
                        .HasColumnType("int");

                    b.HasKey("MaLoaiBV")
                        .HasName("PRIMARY");

                    b.ToTable("articlecategory");
                });

            modelBuilder.Entity("backend.Models.brand", b =>
                {
                    b.Property<string>("MaBrand")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<string>("BrandImages")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenBrand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaBrand")
                        .HasName("PRIMARY");

                    b.ToTable("brand");
                });

            modelBuilder.Entity("backend.Models.cart", b =>
                {
                    b.Property<int>("MaCart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaCart"));

                    b.Property<decimal?>("CostCart")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<bool?>("TrangThaiCart")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("MaCart")
                        .HasName("PRIMARY");

                    b.ToTable("cart");
                });

            modelBuilder.Entity("backend.Models.cartdetail", b =>
                {
                    b.Property<int>("MaCartDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaCartDetail"));

                    b.Property<decimal?>("CostCart")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("MaCart")
                        .HasColumnType("int");

                    b.Property<string>("MaNV")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<int?>("SoLuongSanPham")
                        .HasColumnType("int");

                    b.HasKey("MaCartDetail")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaCart" }, "fk_cartdetail_cart");

                    b.HasIndex(new[] { "MaSanPham" }, "fk_cartdetail_product");

                    b.HasIndex(new[] { "MaNV" }, "fk_cartdetail_staff");

                    b.ToTable("cartdetail");
                });

            modelBuilder.Entity("backend.Models.category", b =>
                {
                    b.Property<string>("MaLoai")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<string>("LoaiImages")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaLoai")
                        .HasName("PRIMARY");

                    b.ToTable("category");
                });

            modelBuilder.Entity("backend.Models.departments", b =>
                {
                    b.Property<string>("MaPhongBan")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<int?>("SoLuongNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("TenPhongBan")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaPhongBan")
                        .HasName("PRIMARY");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("backend.Models.product", b =>
                {
                    b.Property<string>("MaSanPham")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("DonGia")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<int?>("HanBaoHanh")
                        .HasColumnType("int");

                    b.Property<string>("HangHoaImages")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaBrand")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<string>("MaLoai")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<DateOnly?>("NgayNhap")
                        .HasColumnType("date");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool?>("TinhTrangSanPham")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("TrangThaiSanPham")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("MaSanPham")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaBrand" }, "fk_product_brand");

                    b.HasIndex(new[] { "MaLoai" }, "fk_product_category");

                    b.ToTable("product");
                });

            modelBuilder.Entity("backend.Models.register", b =>
                {
                    b.Property<int>("Id_Register")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Register"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Images")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id_Register")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "Email")
                        .IsUnique();

                    b.ToTable("register");
                });

            modelBuilder.Entity("backend.Models.salary", b =>
                {
                    b.Property<int>("MaLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaLuong"));

                    b.Property<decimal?>("LuongCoBan")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("MaNV")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<int?>("Nam")
                        .HasColumnType("int");

                    b.Property<decimal?>("PhuCap")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<int?>("SoNgayCong")
                        .HasColumnType("int");

                    b.Property<int?>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal?>("Thuong")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("TongLuong")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("MaLuong")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaNV" }, "fk_salary_staff");

                    b.ToTable("salary");
                });

            modelBuilder.Entity("backend.Models.staff", b =>
                {
                    b.Property<string>("MaNV")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<string>("CCD")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Id_Register")
                        .HasColumnType("int");

                    b.Property<decimal?>("LuongCoBan")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("MaPhongBan")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<string>("NVImages")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SDT")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenNV")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaNV")
                        .HasName("PRIMARY");

                    b.HasIndex("Id_Register")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "Email")
                        .IsUnique()
                        .HasDatabaseName("Email1");

                    b.HasIndex(new[] { "MaPhongBan" }, "fk_staff_department");

                    b.ToTable("staff");
                });

            modelBuilder.Entity("backend.Models.timekeeping", b =>
                {
                    b.Property<int>("IdChamCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdChamCong"));

                    b.Property<string>("MaNV")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<DateOnly?>("TimeChamCong")
                        .HasColumnType("date");

                    b.HasKey("IdChamCong")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaNV" }, "fk_timekeeping_staff");

                    b.ToTable("timekeeping");
                });

            modelBuilder.Entity("backend.Models.article", b =>
                {
                    b.HasOne("backend.Models.articlecategory", "MaLoaiBVNavigation")
                        .WithMany("article")
                        .HasForeignKey("MaLoaiBV")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_article_category");

                    b.Navigation("MaLoaiBVNavigation");
                });

            modelBuilder.Entity("backend.Models.cartdetail", b =>
                {
                    b.HasOne("backend.Models.cart", "MaCartNavigation")
                        .WithMany("cartdetail")
                        .HasForeignKey("MaCart")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cartdetail_cart");

                    b.HasOne("backend.Models.staff", "MaNVNavigation")
                        .WithMany("cartdetail")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_cartdetail_staff");

                    b.HasOne("backend.Models.product", "MaSanPhamNavigation")
                        .WithMany("cartdetail")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cartdetail_product");

                    b.Navigation("MaCartNavigation");

                    b.Navigation("MaNVNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("backend.Models.product", b =>
                {
                    b.HasOne("backend.Models.brand", "MaBrandNavigation")
                        .WithMany("product")
                        .HasForeignKey("MaBrand")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_product_brand");

                    b.HasOne("backend.Models.category", "MaLoaiNavigation")
                        .WithMany("product")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_product_category");

                    b.Navigation("MaBrandNavigation");

                    b.Navigation("MaLoaiNavigation");
                });

            modelBuilder.Entity("backend.Models.salary", b =>
                {
                    b.HasOne("backend.Models.staff", "MaNVNavigation")
                        .WithMany("salary")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_salary_staff");

                    b.Navigation("MaNVNavigation");
                });

            modelBuilder.Entity("backend.Models.staff", b =>
                {
                    b.HasOne("backend.Models.register", "Register")
                        .WithOne("Staff")
                        .HasForeignKey("backend.Models.staff", "Id_Register")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.departments", "MaPhongBanNavigation")
                        .WithMany("staff")
                        .HasForeignKey("MaPhongBan")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_staff_department");

                    b.Navigation("MaPhongBanNavigation");

                    b.Navigation("Register");
                });

            modelBuilder.Entity("backend.Models.timekeeping", b =>
                {
                    b.HasOne("backend.Models.staff", "MaNVNavigation")
                        .WithMany("timekeeping")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_timekeeping_staff");

                    b.Navigation("MaNVNavigation");
                });

            modelBuilder.Entity("backend.Models.articlecategory", b =>
                {
                    b.Navigation("article");
                });

            modelBuilder.Entity("backend.Models.brand", b =>
                {
                    b.Navigation("product");
                });

            modelBuilder.Entity("backend.Models.cart", b =>
                {
                    b.Navigation("cartdetail");
                });

            modelBuilder.Entity("backend.Models.category", b =>
                {
                    b.Navigation("product");
                });

            modelBuilder.Entity("backend.Models.departments", b =>
                {
                    b.Navigation("staff");
                });

            modelBuilder.Entity("backend.Models.product", b =>
                {
                    b.Navigation("cartdetail");
                });

            modelBuilder.Entity("backend.Models.register", b =>
                {
                    b.Navigation("Staff");
                });

            modelBuilder.Entity("backend.Models.staff", b =>
                {
                    b.Navigation("cartdetail");

                    b.Navigation("salary");

                    b.Navigation("timekeeping");
                });
#pragma warning restore 612, 618
        }
    }
}
